.\"@ s-bsdipa - create or apply binary difference patch.
.
.Dd Dec 20, 2024
.Dt S-BSDIPA 1
.Os
.
.Sh NAME
.Nm s-bsdipa
.Nd create or apply binary difference patch
.
.Sh SYNOPSIS
.
.Nm
.
.Sh DESCRIPTION
.
Please invoke the command without arguments to see usage notes.
.
.Sh AUTHORS
.
.An "Steffen Nurpmeso" Aq steffen@sdaoden.eu .
.
.\" s-ts-mode
